spring:
  application:
    name: extractor
  kafka:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    producer:
      bootstrap-servers: localhost:29092,localhost:29093,localhost:29024
      compression-type: lz4
      properties:
        max.request.size: 26214400
extractor:
  coordinator:
    address: http://localhost:8080
  connection:
    minimum-idle: 2
    maximum-pool-size: 16
  thread-pool-size: 16
logging:
  config: 'classpath:log4j2.yml'
server:
  port: 9088